name: Solar-System-Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env: 
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs: 
  unit-testing:
    name: unit-testing
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: '18'
    
      - name: Install Dependencies
        run: npm install

      - name: Run Test Case
        env:
          MOCHA_FILE: ./test-results/test-results.xml
        run: npm test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: Test-Result
          path: test-results.xml